// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PersonalAccountsColumns holds the columns for the "personal_accounts" table.
	PersonalAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeUint64},
		{Name: "type", Type: field.TypeString, Size: 20},
		{Name: "balance", Type: field.TypeFloat32, Default: 0, SchemaType: map[string]string{"mysql": "decimal(15,4)", "postgres": "numeric"}},
		{Name: "interest", Type: field.TypeFloat32, Default: 0, SchemaType: map[string]string{"mysql": "decimal(10,2)", "postgres": "numeric"}},
	}
	// PersonalAccountsTable holds the schema information for the "personal_accounts" table.
	PersonalAccountsTable = &schema.Table{
		Name:       "personal_accounts",
		Columns:    PersonalAccountsColumns,
		PrimaryKey: []*schema.Column{PersonalAccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "personalaccount_account_id_type",
				Unique:  true,
				Columns: []*schema.Column{PersonalAccountsColumns[3], PersonalAccountsColumns[4]},
			},
		},
	}
	// PersonalAccountTransactionsColumns holds the columns for the "personal_account_transactions" table.
	PersonalAccountTransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "personal_account_id", Type: field.TypeUint64},
		{Name: "type", Type: field.TypeString, Size: 20},
		{Name: "amount", Type: field.TypeFloat32, Default: 0, SchemaType: map[string]string{"mysql": "decimal(10,4)", "postgres": "numeric"}},
		{Name: "status", Type: field.TypeString, Default: "PENDING"},
		{Name: "personal_account_transactions", Type: field.TypeUint64, Nullable: true},
	}
	// PersonalAccountTransactionsTable holds the schema information for the "personal_account_transactions" table.
	PersonalAccountTransactionsTable = &schema.Table{
		Name:       "personal_account_transactions",
		Columns:    PersonalAccountTransactionsColumns,
		PrimaryKey: []*schema.Column{PersonalAccountTransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "personal_account_transactions_personal_accounts_transactions",
				Columns:    []*schema.Column{PersonalAccountTransactionsColumns[7]},
				RefColumns: []*schema.Column{PersonalAccountsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PersonalAccountsTable,
		PersonalAccountTransactionsTable,
	}
)

func init() {
	PersonalAccountTransactionsTable.ForeignKeys[0].RefTable = PersonalAccountsTable
}
