// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PersonalAccountsColumns holds the columns for the "personal_accounts" table.
	PersonalAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeUint64},
		{Name: "type", Type: field.TypeString, Size: 20},
		{Name: "balance", Type: field.TypeFloat32, Default: 0, SchemaType: map[string]string{"mysql": "decimal(15,4)", "postgres": "numeric"}},
		{Name: "interest", Type: field.TypeFloat32, Default: 0, SchemaType: map[string]string{"mysql": "decimal(10,2)", "postgres": "numeric"}},
	}
	// PersonalAccountsTable holds the schema information for the "personal_accounts" table.
	PersonalAccountsTable = &schema.Table{
		Name:       "personal_accounts",
		Columns:    PersonalAccountsColumns,
		PrimaryKey: []*schema.Column{PersonalAccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "personalaccount_account_id_type",
				Unique:  true,
				Columns: []*schema.Column{PersonalAccountsColumns[3], PersonalAccountsColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PersonalAccountsTable,
	}
)

func init() {
}
