// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Savings/ent/personalaccount"
	"Savings/ent/personalaccounttransaction"
	"Savings/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	personalaccountMixin := schema.PersonalAccount{}.Mixin()
	personalaccountMixinFields1 := personalaccountMixin[1].Fields()
	_ = personalaccountMixinFields1
	personalaccountFields := schema.PersonalAccount{}.Fields()
	_ = personalaccountFields
	// personalaccountDescCreatedAt is the schema descriptor for created_at field.
	personalaccountDescCreatedAt := personalaccountMixinFields1[0].Descriptor()
	// personalaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	personalaccount.DefaultCreatedAt = personalaccountDescCreatedAt.Default.(func() time.Time)
	// personalaccountDescUpdatedAt is the schema descriptor for updated_at field.
	personalaccountDescUpdatedAt := personalaccountMixinFields1[1].Descriptor()
	// personalaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	personalaccount.DefaultUpdatedAt = personalaccountDescUpdatedAt.Default.(func() time.Time)
	// personalaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	personalaccount.UpdateDefaultUpdatedAt = personalaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// personalaccountDescAccountID is the schema descriptor for account_id field.
	personalaccountDescAccountID := personalaccountFields[0].Descriptor()
	// personalaccount.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	personalaccount.AccountIDValidator = personalaccountDescAccountID.Validators[0].(func(uint64) error)
	// personalaccountDescType is the schema descriptor for type field.
	personalaccountDescType := personalaccountFields[1].Descriptor()
	// personalaccount.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	personalaccount.TypeValidator = personalaccountDescType.Validators[0].(func(string) error)
	// personalaccountDescBalance is the schema descriptor for balance field.
	personalaccountDescBalance := personalaccountFields[2].Descriptor()
	// personalaccount.DefaultBalance holds the default value on creation for the balance field.
	personalaccount.DefaultBalance = personalaccountDescBalance.Default.(float32)
	// personalaccount.BalanceValidator is a validator for the "balance" field. It is called by the builders before save.
	personalaccount.BalanceValidator = personalaccountDescBalance.Validators[0].(func(float32) error)
	// personalaccountDescInterest is the schema descriptor for interest field.
	personalaccountDescInterest := personalaccountFields[3].Descriptor()
	// personalaccount.DefaultInterest holds the default value on creation for the interest field.
	personalaccount.DefaultInterest = personalaccountDescInterest.Default.(float32)
	// personalaccount.InterestValidator is a validator for the "interest" field. It is called by the builders before save.
	personalaccount.InterestValidator = personalaccountDescInterest.Validators[0].(func(float32) error)
	personalaccounttransactionMixin := schema.PersonalAccountTransaction{}.Mixin()
	personalaccounttransactionMixinFields1 := personalaccounttransactionMixin[1].Fields()
	_ = personalaccounttransactionMixinFields1
	personalaccounttransactionFields := schema.PersonalAccountTransaction{}.Fields()
	_ = personalaccounttransactionFields
	// personalaccounttransactionDescCreatedAt is the schema descriptor for created_at field.
	personalaccounttransactionDescCreatedAt := personalaccounttransactionMixinFields1[0].Descriptor()
	// personalaccounttransaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	personalaccounttransaction.DefaultCreatedAt = personalaccounttransactionDescCreatedAt.Default.(func() time.Time)
	// personalaccounttransactionDescUpdatedAt is the schema descriptor for updated_at field.
	personalaccounttransactionDescUpdatedAt := personalaccounttransactionMixinFields1[1].Descriptor()
	// personalaccounttransaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	personalaccounttransaction.DefaultUpdatedAt = personalaccounttransactionDescUpdatedAt.Default.(func() time.Time)
	// personalaccounttransaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	personalaccounttransaction.UpdateDefaultUpdatedAt = personalaccounttransactionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// personalaccounttransactionDescType is the schema descriptor for type field.
	personalaccounttransactionDescType := personalaccounttransactionFields[1].Descriptor()
	// personalaccounttransaction.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	personalaccounttransaction.TypeValidator = personalaccounttransactionDescType.Validators[0].(func(string) error)
	// personalaccounttransactionDescAmount is the schema descriptor for amount field.
	personalaccounttransactionDescAmount := personalaccounttransactionFields[2].Descriptor()
	// personalaccounttransaction.DefaultAmount holds the default value on creation for the amount field.
	personalaccounttransaction.DefaultAmount = personalaccounttransactionDescAmount.Default.(float32)
	// personalaccounttransaction.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	personalaccounttransaction.AmountValidator = personalaccounttransactionDescAmount.Validators[0].(func(float32) error)
	// personalaccounttransactionDescBalance is the schema descriptor for balance field.
	personalaccounttransactionDescBalance := personalaccounttransactionFields[3].Descriptor()
	// personalaccounttransaction.DefaultBalance holds the default value on creation for the balance field.
	personalaccounttransaction.DefaultBalance = personalaccounttransactionDescBalance.Default.(float32)
	// personalaccounttransaction.BalanceValidator is a validator for the "balance" field. It is called by the builders before save.
	personalaccounttransaction.BalanceValidator = personalaccounttransactionDescBalance.Validators[0].(func(float32) error)
	// personalaccounttransactionDescStatus is the schema descriptor for status field.
	personalaccounttransactionDescStatus := personalaccounttransactionFields[4].Descriptor()
	// personalaccounttransaction.DefaultStatus holds the default value on creation for the status field.
	personalaccounttransaction.DefaultStatus = personalaccounttransactionDescStatus.Default.(string)
}
