// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Savings/ent/personalaccount"
	"Savings/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	personalaccountMixin := schema.PersonalAccount{}.Mixin()
	personalaccountMixinFields1 := personalaccountMixin[1].Fields()
	_ = personalaccountMixinFields1
	personalaccountFields := schema.PersonalAccount{}.Fields()
	_ = personalaccountFields
	// personalaccountDescCreatedAt is the schema descriptor for created_at field.
	personalaccountDescCreatedAt := personalaccountMixinFields1[0].Descriptor()
	// personalaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	personalaccount.DefaultCreatedAt = personalaccountDescCreatedAt.Default.(func() time.Time)
	// personalaccountDescUpdatedAt is the schema descriptor for updated_at field.
	personalaccountDescUpdatedAt := personalaccountMixinFields1[1].Descriptor()
	// personalaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	personalaccount.DefaultUpdatedAt = personalaccountDescUpdatedAt.Default.(func() time.Time)
	// personalaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	personalaccount.UpdateDefaultUpdatedAt = personalaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// personalaccountDescAccountID is the schema descriptor for account_id field.
	personalaccountDescAccountID := personalaccountFields[0].Descriptor()
	// personalaccount.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	personalaccount.AccountIDValidator = personalaccountDescAccountID.Validators[0].(func(uint64) error)
	// personalaccountDescType is the schema descriptor for type field.
	personalaccountDescType := personalaccountFields[1].Descriptor()
	// personalaccount.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	personalaccount.TypeValidator = personalaccountDescType.Validators[0].(func(string) error)
}
