// Code generated by ent, DO NOT EDIT.

package personalaccounttransaction

import (
	"Savings/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// PersonalAccountID applies equality check predicate on the "personal_account_id" field. It's identical to PersonalAccountIDEQ.
func PersonalAccountID(v uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldPersonalAccountID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldType, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float32) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLTE(FieldUpdatedAt, v))
}

// PersonalAccountIDEQ applies the EQ predicate on the "personal_account_id" field.
func PersonalAccountIDEQ(v uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldPersonalAccountID, v))
}

// PersonalAccountIDNEQ applies the NEQ predicate on the "personal_account_id" field.
func PersonalAccountIDNEQ(v uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNEQ(FieldPersonalAccountID, v))
}

// PersonalAccountIDIn applies the In predicate on the "personal_account_id" field.
func PersonalAccountIDIn(vs ...uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldIn(FieldPersonalAccountID, vs...))
}

// PersonalAccountIDNotIn applies the NotIn predicate on the "personal_account_id" field.
func PersonalAccountIDNotIn(vs ...uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNotIn(FieldPersonalAccountID, vs...))
}

// PersonalAccountIDGT applies the GT predicate on the "personal_account_id" field.
func PersonalAccountIDGT(v uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGT(FieldPersonalAccountID, v))
}

// PersonalAccountIDGTE applies the GTE predicate on the "personal_account_id" field.
func PersonalAccountIDGTE(v uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGTE(FieldPersonalAccountID, v))
}

// PersonalAccountIDLT applies the LT predicate on the "personal_account_id" field.
func PersonalAccountIDLT(v uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLT(FieldPersonalAccountID, v))
}

// PersonalAccountIDLTE applies the LTE predicate on the "personal_account_id" field.
func PersonalAccountIDLTE(v uint64) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLTE(FieldPersonalAccountID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldContainsFold(FieldType, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float32) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float32) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float32) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float32) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float32) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float32) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float32) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float32) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLTE(FieldAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.FieldContainsFold(FieldStatus, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.PersonalAccount) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PersonalAccountTransaction) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PersonalAccountTransaction) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PersonalAccountTransaction) predicate.PersonalAccountTransaction {
	return predicate.PersonalAccountTransaction(sql.NotPredicates(p))
}
