// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// PersonalAccount is the predicate function for personalaccount builders.
type PersonalAccount func(*sql.Selector)

// PersonalAccountTransaction is the predicate function for personalaccounttransaction builders.
type PersonalAccountTransaction func(*sql.Selector)
